modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Insane96/ProgressiveBosses/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/progressive-bosses"
authors="${mod_authors}"

# Catalogue icon
itemIcon = "progressivebosses:nether_star_shard"
# Configured background
configBackground = "minecraft:textures/block/soul_sand.png"

description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="insanelib"
    mandatory=true
    versionRange="${lib_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId = "areaeffectcloud3d"
    mandatory = true
    versionRange = "${aec3d_version_range}"
    ordering = "NONE"
    side = "BOTH"
    [dependencies.${mod_id}.mc-publish]
        modrinth="area-effect-clouds-3d" # Modrinth's project slug
        curseforge="area-effect-clouds-3d" # CurseForge's project slug