modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Insane96/ProgressiveBosses/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/progressive-bosses"
logoFile = "icon.png"
authors = "Insane96MCP"
description = '''
Summon and fight stronger bosses
'''

# Catalogue icon
itemIcon = "progressivebosses:nether_star_shard"
# Configured background
configBackground = "minecraft:textures/block/soul_sand.png"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
